version: '3'
services:
    webserver:
        build:
            context: ./code/webserver
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        env_file:
            - .env
